# name: VIDEO ENHANCER

# on:
#   workflow_dispatch:
#   # schedule:
#   #   - cron: '0 7 * * *'    # 12:30 PM IST
#   #   - cron: '0 8 * * *'    # 1:30 PM IST
#   #   - cron: '0 9 * * *'    # 2:30 PM IST
#   #   - cron: '0 10 * * *'   # 3:30 PM IST
#   #   - cron: '0 11 * * *'   # 4:30 PM IST
#   #   - cron: '0 12 * * *'   # 5:30 PM IST
#   #   - cron: '0 13 * * *'   # 6:30 PM IST
#   #   - cron: '0 14 * * *'   # 7:30 PM IST
#   #   - cron: '0 15 * * *'   # 8:30 PM IST
#   #   - cron: '0 16 * * *'   # 9:30 PM IST

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
#     timeout-minutes: 66
#     steps:
#       # Checkout the repository
#       - name: Checkout Code
#         uses: actions/checkout@v4
#         with:
#           sparse-checkout: |
#             VIDEO_TO_UPLOAD/
#             ENHANCED_VIDEOS/
#             VIDEO_ENHANCER/
#             counter.txt
#             requirements.txt
#           fetch-depth: 1

#       # Read the counter value and set sparse-checkout for the specific video
#       - name: Configure Sparse Checkout for Specific Video
#         run: |
#           VIDEO_NUMBER=$(cat counter.txt)
#           echo "Setting sparse-checkout for Video_${VIDEO_NUMBER}.mp4"
#           echo "VIDEOS/Video_${VIDEO_NUMBER}.mp4" >> .git/info/sparse-checkout
#           git sparse-checkout reapply

#       # Set up Python environment
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12.9'  # Specify the Python version you need
      
#       # Install the necessary packages
#       - name: Installed package list
#         run: apt list --installed

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#          python3 -m pip install --upgrade pip
#          pip3 install -r requirements.txt

#       # Run your Python script
#       - name: Run Python script
#         run: python3 VIDEO_ENHANCER/video_enhancer.py

#       # Commit changes if ENHANCED_VIDEOS was modified, pull, and push the modified changes.
#       - name: Commit and Push Changes
#         run: |
#           git config --local user.name "github-actions"
#           git config --local user.email "github-actions@github.com"
#           git add ENHANCED_VIDEOS
#           git commit -m "Update ENHANCED_VIDEOS after processing" || echo "No changes to commit"
#           git pull --rebase origin main || echo "No changes to pull"
#           git push || echo "No changes to push"
          
#       # Commit changes if VIDEO_TO_UPLOAD was modified, pull, and push the modified changes.
#       - name: Commit and Push Changes
#         run: |
#           git config --local user.name "github-actions"
#           git config --local user.email "github-actions@github.com"
#           git add VIDEO_TO_UPLOAD
#           git commit -m "Update VIDEO_TO_UPLOAD after processing" || echo "No changes to commit"
#           git pull --rebase origin main || echo "No changes to pull"
#           git push || echo "No changes to push"